### ISSUE TITLE
Incorrect driver instantiated

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/driver#102]
**Describe the bug**
If a driver entrypoint set of `require`s includes another class extending `PlaceOS::Driver`, the external driver is instantiated in place of the one defined in the entrypoint.

**Your environment**
dd8cbf3

**Expected behavior**
The driver defined in the entrypoint should always be provided, regardless of dependency tree.

**Additional context**
Workaround possible be re-ordering requires. Example in https://github.com/PlaceOS/drivers/commit/246c1afd1f5cd58511ca580186617ab13d01ea11#diff-a71518107f3a70bc9b544c75c80bdffa8e8e0def85f68c3277f763d3dd82da32

**Comment by caspiano** [comment]
Related #84

**Comment by caspiano** [comment]
This is primarily an issue with the deviancy of PlaceOS drivers from the norm of crystal apps.

This bug is more of a gotcha, and can be worked around, but would be worth fixing in the interest of reducing cognitive load when developing drivers.
