### ISSUE TITLE
Initial connected state not set

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/driver#13]
When first instantiated, an initial `:connected` state is not set if the transport cannot establish a connection. This results in a module being offline, but not correctly reflecting this in it's status, or firing a `disconnected` callback.

The cause of this is state change detection in [`Queue#online=`](https://github.com/PlaceOS/driver/blob/master/src/driver/queue.cr#L31-L38), as [`@online` initializes as `false`](https://github.com/PlaceOS/driver/blob/master/src/driver/queue.cr#L21).

**Comment by KimBurgess** [comment]
@stakach you're much more familiar with this than I am. One possible solution I can see is to add an `@initialized` flag that flips to true on the first call to `#online=`. On that initial run it can then still hit the callback so that the state sets drivers' internal callback fires.

This keeps the change internal only as opposed to change the existing online status from a `Bool` -> some form of ternary state (`Bool?` / `Enum`).

Can you see this causing any issues elsewhere?

**Comment by stakach** [comment]
that's a good point, I think we use `Bool?` as we can use an initial state of `nil` to represent uninitialized
