### ISSUE TITLE
Socket does not re-establish following disconnect

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/driver#16]
For drivers built on the TCP transport, the underlying connecting does not auto-reconnect when closed by the server side.

Module state correctly updates to connected == `false`, however logs do not show any attempts to reconnect.

There appears to be logic for re-establishing this connecting, however from the behaviour observed, the [call to set the queue offline](https://github.com/PlaceOS/driver/blob/016c023c5f4528a1e9faa4381e0a192674c9639a/src/driver/transport/tcp.cr#L128-L129) may be blocking indefinitely.

**Comment by stakach** [comment]
@KimBurgess are you able to deep dive on this?
I don't believe there should be any possibility for `@queue.online = false` to block.

it performs the `disconnected` [callback](https://github.com/PlaceOS/driver/blob/016c023c5f4528a1e9faa4381e0a192674c9639a/src/driver/driver_manager.cr#L189) before attempting to re-connect

**Comment by stakach** [comment]
is this something you've been able to replicate on the dev-env / partner-envs with the driver revision using `simple_retry`?

**Comment by KimBurgess** [comment]
Yep. Have replicated here with partner env running the current beta containers.

If I sh into core, can also see the shard.lock there and confirmed it's definitely using simply_retry.

I'll dive a little deeper and see what I can find.

**Comment by stakach** [comment]
when `sh`'d into core you'll be able to edit the lib folder too to add additional debug logs and `begin` `catch` blocks

stopping the module, deleting the driver and starting it or right clicking on the module and selecting `load_module` should trigger a re-compile

**Comment by KimBurgess** [comment]
All methods are being called correctly / not blocking. Issue is due to [`@socket.closed?`](https://github.com/PlaceOS/driver/blob/6779db86ecff990652ba49dc7b7b4abc0d1b2f8e/src/placeos-driver/transport/tcp.cr#L22) reporting as `false` when reconnect is attempted.

The read loop is exiting due to an `IO::Error` (expected), but in the case of an unclean disconnect the local socket will still be in a half-open state.

**Comment by stakach** [comment]
Ahh cool. I assume we can call `socket.close` in the rescue
