### ISSUE TITLE
HTTP requests in `on_load` cause specs to block

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/driver#37]
If a driver attempts to exec a HTTP request during load, the spec runner blocks.

![98F4AB77-3C92-4F55-8798-8E4E2228ED15](https://user-images.githubusercontent.com/843652/88117453-87481000-cbfe-11ea-8e2f-a9b33e4cd2e3.jpeg)

The first `expect_http_request` does not appear to be entered when this occurs.

Current workaround is to defer the request with a `schedule.in(...)`

**Comment by stakach** [comment]
transport is not expected to be ready in `on_load`
transport is ready in the `connected` callback

this might still not resolve the test runner but worth testing

**Comment by KimBurgess** [comment]
Cool. That makes sense - I’ll be sure to highlight that in the docs.

For the spec blocking from a quick glance it looks like a `Fiber.yield` prior to [calling `on_load` here](https://github.com/PlaceOS/driver/blob/dacc2fef674bcf00f9ebe1407b89b71078041867/src/placeos-driver/driver-specs/mock_driver.cr#L260) may help out. That will give the [server a chance to spin up](https://github.com/PlaceOS/driver/blob/dacc2fef674bcf00f9ebe1407b89b71078041867/src/placeos-driver/driver-specs/runner.cr#L103) prior to being flung a request, even if this is not a supported point to do so.
