### ISSUE TITLE
Cannot set empty strings as status values

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/driver#67]
**Describe the bug**
When attempting to place an empty string on a status key the current implementations of both [`redis-storage`](https://github.com/PlaceOS/driver/blob/7ebc7514c19149dc1eabd03d57b7648bacaa2e43/src/placeos-driver/storage/redis-storage.cr#L21) and [`edge-storage`](https://github.com/PlaceOS/driver/blob/7ebc7514c19149dc1eabd03d57b7648bacaa2e43/src/placeos-driver/storage/edge-storage.cr#L16) rewrite this as `nil`.

**Expected behavior**
The value should be set as passed.

**Additional context**
These are semantically different values with both being useful for driver authors.

**Comment by stakach** [comment]
yeah this should be allowed, but it's not an issue I don't think as an empty string in JSON is `""`
so it does have presence
