### ISSUE TITLE
Provide `before_request` hook for http transport

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/driver#7]
To provide the ability to insert auth headers and other common request items it would be useful to have access to a `before_request` hook as part of the http transport.

This should ideally mirror the [`HTTP::Client#before_request`](https://crystal-lang.org/api/0.34.0/HTTP/Client.html#before_request(&callback:HTTP::Request-%3E)-instance-method) api, and pass through to this.

A minimal implementation may be to change change the visibility of [`PlaceOS::Driver::TransportHTTP#with_shared_client`](https://github.com/PlaceOS/driver/blob/e8cb211a2004ae84a9b5f2e943e2a6040caac170/src/driver/transport/http.cr#L157-L161), however it may be neater to keep a registration of these callbacks so that they can reapplied when a new client is created (e.g. for a concurrent request).

**Comment by caspiano** [comment]
AFAIK, this has been implemented. Paging @stakach

**Comment by stakach** [comment]
Thanks, yes there is a helper implemented
`transport.before_request { |http_request| modify_request http_request }`

example usage: https://github.com/PlaceOS/drivers/blob/5bcf95b9f5f9349b5e7e38b22bd260e985a875e5/drivers/lenel/open_access.cr#L30
