### ISSUE TITLE
Support parsing inter-driver requests into concrete types

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/driver#74]
Currently requests executed via `Proxy::Driver` return a `JSON::Any`.

https://github.com/PlaceOS/driver/blob/f60235a66ad9f1f89ff9ca1badea0919670e9f8e/src/placeos-driver/proxy/driver.cr#L111

To remove the need for double parsing / manual extraction of this, it would be useful to be able to optionally specify a type to deserialise into. Interactions using interfaces should also use this same mechanism to provide appropriate return types as specified by the interface.

**Comment by caspiano** [comment]
Unlikely to implement this. Has been raised in internal discussions several times.
