### ISSUE TITLE
Add support for interactive auth in SSH transport

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/driver#8]
Currently the SSH transport only supports `password` or `publickey` authentication. Some devices - specifically Cisco WebEx endpoints - use `keyboard-interactive` in place of `password`.

Note: this has a dependency on spider-gazelle/ssh2.cr#8

**Comment by stakach** [comment]
support added to the base lib https://github.com/spider-gazelle/ssh2.cr/commit/0ea54780b1adfa867f4367785771e06b36afe731

**Comment by stakach** [comment]
fixed in #12
