### ISSUE TITLE
SSH transport ignores supported auth methods

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/driver#9]
When establishing a connection, [supported auth methods are retrieved](https://github.com/PlaceOS/driver/blob/master/src/driver/transport/ssh.cr#L82) from the server, but then ignored.

Transport should only attempt to authenticate using server-supported methods.

**Comment by stakach** [comment]
Yeah it might actually not work for no-auth either looking at the method:
https://github.com/spider-gazelle/ssh2.cr/blob/5a9252ec128de1fc7141b8b2225da4cedf9a4e75/src/session.cr#L124

returns a string or a bool but not sure what the string looks like.

**Comment by stakach** [comment]
I'll do a bit of digging

**Comment by KimBurgess** [comment]
From looking at the behaviour of a Cisco endpoint just then, it was getting back the list of support methods as expected. Behaviour likely needs to be:
`false`: nothing to do, already authed
`string`: peel off server-side supported methods and attempt in sequence
`true`: step through all methods _we_ support.
